# fly.toml app configuration file generated for foodorderingapp on 2023-05-11T22:23:20+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "foodorderingapp"
primary_region = "yyz"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
